// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/blog/[slug]/index.tsx";
import * as $2 from "./routes/blog/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/info.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/Menu/Menu.tsx";
import * as $$3 from "./islands/Menu/linksAvailable.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/blog/[slug]/index.tsx": $1,
    "./routes/blog/index.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/info.tsx": $4,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/Menu/Menu.tsx": $$2,
    "./islands/Menu/linksAvailable.ts": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
