"use strict";
// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.
Object.defineProperty(exports, "__esModule", { value: true });
var $_404 = require("./routes/_404.tsx");
var $_app = require("./routes/_app.tsx");
var $_layout = require("./routes/_layout.tsx");
var $api_highscore_index = require("./routes/api/highscore/index.ts");
var $blog_slug_index = require("./routes/blog/[slug]/index.tsx");
var $blog_layout = require("./routes/blog/_layout.tsx");
var $blog_index = require("./routes/blog/index.tsx");
var $experiments_layout = require("./routes/experiments/_layout.tsx");
var $experiments_flappy = require("./routes/experiments/flappy.tsx");
var $experiments_grid = require("./routes/experiments/grid.tsx");
var $experiments_index = require("./routes/experiments/index.tsx");
var $index = require("./routes/index.tsx");
var $info = require("./routes/info.tsx");
var $Footer = require("./islands/Footer.tsx");
var $Header = require("./islands/Header.tsx");
var $Menu_Menu = require("./islands/Menu/Menu.tsx");
var $flappy_GameWindowProps = require("./islands/flappy/GameWindowProps.tsx");
var $flappy_components_fun_input = require("./islands/flappy/components/fun-input.tsx");
var $flappy_components_instructions = require("./islands/flappy/components/instructions.tsx");
var $flappy_components_mouse_click_icon = require("./islands/flappy/components/mouse-click-icon.tsx");
var $flappy_components_space_click_icon = require("./islands/flappy/components/space-click-icon.tsx");
var $flappy_components_submit_highscore = require("./islands/flappy/components/submit-highscore.tsx");
var $flappy_logic_collision = require("./islands/flappy/logic/collision.ts");
var $flappy_logic_constants = require("./islands/flappy/logic/constants.ts");
var $flappy_logic_draw = require("./islands/flappy/logic/draw.ts");
var $flappy_logic_obstacles = require("./islands/flappy/logic/obstacles.ts");
var manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/_layout.tsx": $_layout,
        "./routes/api/highscore/index.ts": $api_highscore_index,
        "./routes/blog/[slug]/index.tsx": $blog_slug_index,
        "./routes/blog/_layout.tsx": $blog_layout,
        "./routes/blog/index.tsx": $blog_index,
        "./routes/experiments/_layout.tsx": $experiments_layout,
        "./routes/experiments/flappy.tsx": $experiments_flappy,
        "./routes/experiments/grid.tsx": $experiments_grid,
        "./routes/experiments/index.tsx": $experiments_index,
        "./routes/index.tsx": $index,
        "./routes/info.tsx": $info,
    },
    islands: {
        "./islands/Footer.tsx": $Footer,
        "./islands/Header.tsx": $Header,
        "./islands/Menu/Menu.tsx": $Menu_Menu,
        "./islands/flappy/GameWindowProps.tsx": $flappy_GameWindowProps,
        "./islands/flappy/components/fun-input.tsx": $flappy_components_fun_input,
        "./islands/flappy/components/instructions.tsx": $flappy_components_instructions,
        "./islands/flappy/components/mouse-click-icon.tsx": $flappy_components_mouse_click_icon,
        "./islands/flappy/components/space-click-icon.tsx": $flappy_components_space_click_icon,
        "./islands/flappy/components/submit-highscore.tsx": $flappy_components_submit_highscore,
        "./islands/flappy/logic/collision.ts": $flappy_logic_collision,
        "./islands/flappy/logic/constants.ts": $flappy_logic_constants,
        "./islands/flappy/logic/draw.ts": $flappy_logic_draw,
        "./islands/flappy/logic/obstacles.ts": $flappy_logic_obstacles,
    },
    baseUrl: import.meta.url,
};
exports.default = manifest;
